name: Echo

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo"
        run: echo "Foo"
