name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: List files
      run: ls
    - name: Echo
      if: github.event_name != 'schedule' || github.event.repository.private
      run: echo "Foo"
