name: Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - uses: statsig-io/statsig-publish-sdk-action@v1.2
        with:
          gh-token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
