name: Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: statsig-io/statsig-publish-sdk-action@main
        with:
          gh-token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
