name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  call-echo:
    if: github.event.repository.private
    uses: statsig-io/test-sdk-repo-private/.github/workflows/echo.yml@main
